# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5ea884880f9b12cf8d01fed7aff42c010029f214f70fae6b601dd343a8e06c9c2ff0ddb6ff35e4b983055bf34f717844e5dc1bf22bc57b28bd05274d5c2d302

test:
  secret_key_base: 134e28f420e09009d39b5c31b6e803ab8ceac423c9473fbb0d49ace2b0b5700d9737b525cc91e532ac693b253ccc2e40891419e2c35e3955d458cc5cb4988e99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
